<?php

declare(strict_types=1);

namespace CombatUI\CombatUIOpenDxpBundle\Tests\Unit\Theme;

use Codeception\Test\Unit;
use CombatUI\CombatUIOpenDxpBundle\Theme\ThemeCssGenerator;

final class ThemeCssGeneratorTest extends Unit
{
    private ThemeCssGenerator $generator;

    protected function _before(): void
    {
        $this->generator = new ThemeCssGenerator();
    }

    public function testEmptyOverridesProduceNoCss(): void
    {
        $this->assertSame('', $this->generator->generate([]));
    }

    public function testValueOverridesLandInRootOnly(): void
    {
        $css = $this->generator->generate(['--cui-space-1' => ['value' => '0.5rem']]);

        $this->assertStringContainsString(":root {\n  --cui-space-1: 0.5rem;\n}", $css);
        $this->assertStringNotContainsString('data-theme', $css);
        $this->assertStringNotContainsString('@media', $css);
    }

    public function testLightColorOverridesLandInRootAndLightPin(): void
    {
        $css = $this->generator->generate(['--cui-color-accent' => ['light' => 'oklch(60% 0.2 30deg)']]);

        $this->assertStringContainsString(":root {\n  --cui-color-accent: oklch(60% 0.2 30deg);\n}", $css);
        $this->assertStringContainsString(
            ":where(:root[data-theme=\"light\"], [data-theme=\"light\"]) {\n  --cui-color-accent: oklch(60% 0.2 30deg);\n}",
            $css,
        );
    }

    public function testDarkColorOverridesLandInMediaQueryAndDarkPin(): void
    {
        $css = $this->generator->generate(['--cui-color-accent' => ['dark' => 'oklch(70% 0.2 30deg)']]);

        $this->assertStringContainsString(
            "@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n    --cui-color-accent: oklch(70% 0.2 30deg);\n  }\n}",
            $css,
        );
        $this->assertStringContainsString(
            ":where(:root[data-theme=\"dark\"], [data-theme=\"dark\"]) {\n  --cui-color-accent: oklch(70% 0.2 30deg);\n}",
            $css,
        );
        $this->assertStringNotContainsString(":root {\n", $css);
    }

    public function testMixedOverridesMirrorTheFrameworkStructure(): void
    {
        $css = $this->generator->generate([
            '--cui-radius-1' => ['value' => '0.5rem'],
            '--cui-color' => [
                'light' => 'oklch(20% 0.04 264deg)',
                'dark' => 'oklch(98% 0.01 259deg)',
            ],
        ]);

        $expected = <<<'CSS'
/* Generated by the Combat UI theme editor. Loads after the framework tokens. */
:root {
  --cui-radius-1: 0.5rem;
  --cui-color: oklch(20% 0.04 264deg);
}
:where(:root[data-theme="light"], [data-theme="light"]) {
  --cui-color: oklch(20% 0.04 264deg);
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --cui-color: oklch(98% 0.01 259deg);
  }
}
:where(:root[data-theme="dark"], [data-theme="dark"]) {
  --cui-color: oklch(98% 0.01 259deg);
}

CSS;

        $this->assertSame(str_replace("\r\n", "\n", $expected), $css);
    }
}
