<?php

declare(strict_types=1);

/*
 * Combat UI OpenDXP Bundle
 *
 * This source file is licensed under the GNU General Public License version 3 (GPLv3).
 *
 * @copyright Copyright (c) 2026 Combat Jongerenmarketing en -communicatie B.V. (https://www.combat.nl)
 * @license   https://www.gnu.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
 */

namespace CombatUI\CombatUIOpenDxpBundle\Theme;

/**
 * Turns token overrides into a stylesheet that loads after the framework CSS. The selectors
 * mirror the structure of the framework's tokens.css exactly, so an override wins over the
 * corresponding framework declaration by source order in every theme context:
 *
 *  - light values into `:root` plus the explicit light pin,
 *  - dark values into the prefers-color-scheme media query plus the explicit dark pin.
 */
final class ThemeCssGenerator
{
    private const LIGHT_PIN_SELECTOR = ':where(:root[data-theme="light"], [data-theme="light"])';

    private const DARK_PIN_SELECTOR = ':where(:root[data-theme="dark"], [data-theme="dark"])';

    private const DARK_AUTO_SELECTOR = ':root:not([data-theme="light"])';

    /**
     * @param array<string, array<string, string>> $overrides validated token overrides
     */
    public function generate(array $overrides): string
    {
        $root = [];
        $light = [];
        $dark = [];
        foreach ($overrides as $name => $slots) {
            if (isset($slots['value'])) {
                $root[$name] = $slots['value'];
            }
            if (isset($slots['light'])) {
                $root[$name] = $slots['light'];
                $light[$name] = $slots['light'];
            }
            if (isset($slots['dark'])) {
                $dark[$name] = $slots['dark'];
            }
        }

        if ($root === [] && $dark === []) {
            return '';
        }

        $css = "/* Generated by the Combat UI theme editor. Loads after the framework tokens. */\n";
        if ($root !== []) {
            $css .= $this->rule(':root', $root);
        }
        if ($light !== []) {
            $css .= $this->rule(self::LIGHT_PIN_SELECTOR, $light);
        }
        if ($dark !== []) {
            $css .= "@media (prefers-color-scheme: dark) {\n"
                . $this->rule(self::DARK_AUTO_SELECTOR, $dark, '  ')
                . "}\n";
            $css .= $this->rule(self::DARK_PIN_SELECTOR, $dark);
        }

        return $css;
    }

    /**
     * @param array<string, string> $declarations
     */
    private function rule(string $selector, array $declarations, string $indent = ''): string
    {
        $lines = [];
        foreach ($declarations as $name => $value) {
            $lines[] = sprintf('%s  %s: %s;', $indent, $name, $value);
        }

        return sprintf("%s%s {\n%s\n%s}\n", $indent, $selector, implode("\n", $lines), $indent);
    }
}
